# -*- coding: utf-8 -*-
"""
/***************************************************************************
 BiomaStatsQGIS
                                 A QGIS plugin
 Sistema de download e análise para mapas de uso e ocupação do solo.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-01-31
        copyright            : (C) 2025 by João V. V. Stefanini / CeMECA-UFSCar
        email                : joao.stefanini@estudante.ufscar.br
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load BiomaStatsQGIS class from file BiomaStatsQGIS.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .bioma_stats_QGIS import BiomaStatsQGIS
    return BiomaStatsQGIS(iface)
